version: '2.4'
services:
  hannablog:
    image: wordpress
    restart: always
    container_name: hannablog
    mem_limit: 200m
    environment:
      VIRTUAL_HOST: hannablog.oktibor.com
      VIRTUAL_PORT: 80
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: hannablog
      WORDPRESS_TABLE_PREFIX: hanna_
      WORDPRESS_CONFIG_EXTRA: |
          if (isset($$_SERVER['HTTP_X_FORWARDED_FOR'])) {
               $$http_x_headers = explode(',', $$_SERVER['HTTP_X_FORWARDED_FOR']);
               $$_SERVER['REMOTE_ADDR'] = $$http_x_headers[0];
          }
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./.htaccess:/var/www/html/.htaccess
    networks:
      - nginx
      - mysql

networks:
  nginx:
   external: true
  mysql:
   external: true
